pipeline{
    agent {
  label 'jenkins-node-1'
 }
    stages{
        stage('Build') {
            steps{
                sh 'npm install'
            }
        }

        stage('Test') {
            steps{
                sh './jenkins/scripts/test.sh'
            }
        }
    }
}